services:
    ct.manager.user:
        class: CelciusTech\CoreBundle\Manager\UserManager
        arguments: [@service_container]

    ct.twig.core_extension:
        class: CelciusTech\CoreBundle\Twig\CoreExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    ct.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: [@exercise_html_purifier.default]

    ct.form.type.purified_textarea:
        class: CelciusTech\CoreBundle\Form\Type\PurifiedTextareaType
        arguments: [@ct.form.transformer.html_purifier]
        tags:
          - { name: form.type, alias: purified_textarea }

    ct.form.type.purified_text:
        class: CelciusTech\CoreBundle\Form\Type\PurifiedTextType
        arguments: [@ct.form.transformer.html_purifier]
        tags:
          - { name: form.type, alias: purified_text }
